name = "cloudflare-file-hosting"
main = "index.js"
compatibility_date = "2025-06-02"

[[d1_databases]]
binding = "VISITOR_DB"
database_name = "visitor_db"
database_id = "d90ba927-4ee4-4f9e-a766-6e19dc549984"
